[RunSvc]
JobName = "Test beam example job"
BeamType = "IAEA"
SimConfigFile = "/jobs/testbeam/angle_scan_plan.toml"
SimConfigPrefix = "SimConditions"
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH pc location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH pc location
PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # 121 jh workstation file location

NTupleAnalysis = true 

[PatientGeometry]
Type = "Dose3D"
ConfigPrefix = "Dose3D"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 0.0
EnviromentSizeX = 400.0
EnviromentSizeY = 400.0
EnviromentSizeZ = 400.0
EnviromentMedium = "G4_Galactic"

[Dose3D_Detector]
TranslationInLocalFrame = [0.0,0.0,0.0] # In mm
Voxelization = [1,1,3] # Number of cels in every direction

[Dose3D_Layer]
MRowShift = true
MLayerShift = true

[Dose3D_Cell]
Medium = "PMMA" #G4_WATER, PMMA
Voxelization = [10,10,10]