[RunSvc]
JobName = "Single file tompl run test"
BeamType = "gps" # "gps" IAEA 
SimConfigPrefix = "SimConditions"
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH pc location
GpsMacFileName = "/home/g4rt/installation_files/dose3d-geant4-linac/scripts/gps_alpha_5390_kev.mac" # AGH JH File
# PhspInputFileName = "/mnt/e/dose3d/TNSIM157_3x3s2-f0" # lokalizacja Michala
# PhspInputFileName = "/mnt/d/Torrenty/FMDoseLab_3x3_6_110s2-f0" # jh home file 

NTupleAnalysis = true 

[PatientGeometry]
Type = "WaterPhantom" # "WaterPhantom" "Dose3D"
ConfigPrefix = "WP" # WP  Dose3D
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 50.0
EnviromentSizeX = 100.0
EnviromentSizeY = 100.0
EnviromentSizeZ = 100.0
EnviromentMedium = "G4_Galactic"

[Dose3D_Detector]
TranslationInLocalFrame = [0.0,0.0,-100.0] # In mm
Voxelization = [4,2,5] # Number of cels in every direction

[Dose3D_Layer]
MRowShift = false
MLayerShift = false

[Dose3D_Cell]
Medium = "PMMA" #G4_WATER, PMMA
Voxelization = [10,2,10]


[WP_Detector]
TranslationFromCentre = [0.0,0.0,0.0] # In mm
Voxelization = [100,100,100] # Number of cels in every direction
Size = [100.0,100.0,100.0]
Medium = "PMMA" #G4_WATER, PMMA

[WP_Scoring]
FullVolume = true
FarmerDoseCalibration = false


[SimConditions_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0,90.0,180.0,270.0,300.0,315.0,330.0,345.0,0.0,15.0,30.0,45.0,60.0,75.0,90.0]
Particle_Counter_Per_Control_Point = [50] #50000,5000000,5000000,5000000,5000000,5000000,5000000,5000000,5000000]
