[RunSvc]
JobName = "Single file tompl run test"
BeamType = "gps"
SimConfigPrefix = "SimConditions"
PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
GpsMacFileName = "/home/g4rt/instal/dose3d-geant4-linac/scripts/gps.mac"
Physics = "LowE_Penelope" #"LowE_Penelope"
PrintProgressFrequency = 0.001

NTupleAnalysis = true 
BeamAnalysis = true 
# PrimariesAnalysis = true 

FieldSize = 60 # mm

[PatientGeometry]
Type = "Dose3D" # "WaterPhantom" "Dose3D"
ConfigPrefix = "Dose3D" # WP  Dose3D
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 42.0
EnviromentSizeX = 50.0
EnviromentSizeY = 50.0
EnviromentSizeZ = 288.0
EnviromentMedium = "PMMA"

[Dose3D_Detector]
TranslationInLocalFrame = [0.0,0.0,-137.0] # In mm
Voxelization = [1,1,10] # Number of cels in every direction

[Dose3D_Layer]
MRowShift = false
MLayerShift = false

[Dose3D_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [1,1,1]

[SimConditions_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0,90.0,180.0,270.0] #300.0,315.0,330.0,345.0,0.0,15.0,30.0,45.0,60.0,75.0,90.0]
Particle_Counter_Per_Control_Point = [2e3,5e5,5e5,5e5] #50000,5000000,5000000,5000000,5000000,5000000,5000000,5000000,5000000]

