[RunSvc]
JobName = "PLA50"
BeamType = "IAEA" # "gps" IAEA 
SimConfigPrefix = "SimConditions"
PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH pc location
# PhspInputFileName = "/mnt/c/Users/Madej/Desktop/shared/TNSIM157_3x3s2-f0" #Pawel
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH JH File
# PhspInputFileName = "/mnt/e/dose3d/TNSIM157_3x3s2-f0" # lokalizacja Michala
# PhspInputFileName = "/mnt/d/Torrenty/FMDoseLab_3x3_6_110s2-f0" # jh home file 
PrintProgressFrequency = 0.2
NTupleAnalysis = true

[PatientGeometry]
Type = "Dose3D" # "WaterPhantom" "Dose3D"
ConfigPrefix = "Dose3D" # WP  Dose3D
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 0.0
EnviromentSizeX = 410.0
EnviromentSizeY = 410.0
EnviromentSizeZ = 410.0
EnviromentMedium = "G4_WATER"

[Dose3D_Detector]
TranslationInLocalFrame = [0.0,0.0,-200.0] # In mm
Voxelization = [1,1,15] # Number of cels in every direction

[Dose3D_Layer]
MRowShift = false
MLayerShift = false

[Dose3D_Cell]
Medium = "PMMA" #G4_WATER, PMMA
Voxelization = [1,1,1]

[WP_Detector]
TranslationFromCentre = [0.0,0.0,0.0] # In mm
Voxelization = [1,1,1] # Number of cels in every direction
Size = [400.0,400.0,400.0]
Medium = "G4_WATER" #G4_WATER, PMMA

[WP_Scoring]
FullVolume = false
FarmerDoseCalibration = true


[SimConditions_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0,90.0,180.0,270.0,300.0,315.0,330.0,345.0,0.0,15.0,30.0,45.0,60.0,75.0,90.0]
Particle_Counter_Per_Control_Point = [1e5,5e5,5e5,5e5] #50000,5000000,5000000,5000000,5000000,5000000,5000000,5000000,5000000]
