[RunSvc]
JobName = "flsz_propagation_study"
BeamType = "IAEA" # "gps" IAEA 
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
# PhspInputFileName = "/etude/brachwal/iaea-phsp/TNSIM157_10x10s2-f0" # AGH LHCBD2 location
PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH BR location
PrintProgressFrequency = 0.01
NTupleAnalysis = true 
FieldType = "Rectangular"
# FieldType = "Elipsoidal"
FieldSizeA = 20 # mm
FieldSizeB = 20 # mm

[PatientGeometry]
Type = "D3DDetector"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 200.0
EnviromentSizeX = 50.0
EnviromentSizeY = 50.0
EnviromentSizeZ = 400.0
EnviromentMedium = "G4_Galactic"

[D3DDetector_Detector]
TranslationInLocalFrame = [0.0,0.0,-200.0] # In mm
# Voxelization = [3,3,20] # Number of cels in every direction
Voxelization = [3,3,3] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [10,10,10]
TracksAnalysis = false

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0]
Particle_Counter_Per_Control_Point = [1e4]

[LogSvc_D3DCell]
LogLevel = "debug"
