[book]
title = "G4RT Documentation"
authors = ["Dose3D Team"]
language = "en"
multilingual = false
src = "."

[build]
build-dir = "book"
create-missing = true
extra-watch-dirs = ["./core", "./data", "./docs", "./externals", "./submodules"]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/jhajduga/jhajduga.github.io"
git-repository-icon = "fa-github"
favicon = "favicon.ico"
additional-css = ["externals/theme/custom.css"]
additional-js = ["externals/theme/custom.js"]

[output.html.search]
enable = true

[output.html.fold]
enable = true

[preprocessor.admonish]
command = "mdbook-admonish"

[preprocessor.toc]
command = "mdbook-toc"

[preprocessor.mermaid]
command = "mdbook-mermaid"
