[book]
title = "G4RT Documentation"
authors = ["Dose3D Team"]
language = "en"
multilingual = false
src = "."  # root as source

[build]
build-dir = "book"
create-missing = true
extra-watch-dirs = ["./core", "./data", "./docs", "./externals", "./submodules"]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
fold = true

[output.html.search]
enable = true

[preprocessor.admonish]
command = "mdbook-admonish"

[preprocessor.toc]
command = "mdbook-toc"

[preprocessor.mermaid]
command = "mdbook-mermaid"
