[RunSvc]
JobName = "srunet3d_4x4x2_64x64x64_beam2"
BeamType = "IAEA"
# PhspInputFileName = "/mnt/c/Users/brachwal-agh/Workspace/IAEA/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH Dell-XPS location
# PhspInputFileName = "/etude/brachwal/iaea-phsp/TNSIM157_3x3s2-f0" # AGH LHCBD2 location
PhspInputFileName = "/etude/brachwal/iaea-phsp/TNSIM157_10x10s2-f0" # AGH LHCBD2 location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH BR location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH BR location
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
# PhspInputFileName = "/mnt/e/phsp/TNSIM157_3x3s2-f0" # JH Home File
PhspEvtVrtxMultiplicityTreshold = 20
PrintProgressFrequency = 0.05
GenerateCT = true
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true

[GeoSvc]
BuildLinac = true
BuildPatient = true

[PatientGeometry]
Type = "D3DDetector"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 0.0
EnviromentSizeX = 64.0
EnviromentSizeY = 64.0
EnviromentSizeZ = 64.0
EnviromentMedium = "Usr_G4AIR20C"

[D3DDetector_Detector]
TranslationInLocalFrame = [0.0,0.0,0.0] # In mm
Voxelization = [4,4,2] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "RMPS470"
Voxelization = [10,10,10]
TracksAnalysis = false
CellVoxelisedScorer = true

[RunSvc_Plan] # paths can be relative (to PROJECT_DATA) or absolute
# nParticles = [1e4] # Per Control Point
PlanInputFile = [
        "plan/custom/prostate/prostate_imrt_beam2_cp0.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp2.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp1.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp3.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp4.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp5.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp6.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp7.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp8.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp9.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp10.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp11.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp12.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp13.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp14.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp15.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp16.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp17.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp18.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp19.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp20.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp21.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp22.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp23.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp24.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp25.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp26.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp27.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp28.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp29.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp73.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp74.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp75.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp76.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp77.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp78.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp79.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp80.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp81.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp82.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp83.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp84.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp85.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp86.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp87.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp88.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp89.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp90.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp91.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp92.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp93.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp94.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp95.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp96.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp97.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp98.dat",
        "plan/custom/prostate/prostate_imrt_beam2_cp99.dat"
]