# 
# This is dockerfile to build an image for dose3d cross-project environment
# 
# Build locally:
# docker build --tag 'g4rt:v1r0' . -f docker/g4rt.Dockerfile
#
# RunInteractively and Remove it Once the Process is Complete
# docker run -it --rm g4rt:v1r0 /bin/bash

FROM ubuntu:22.04
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

LABEL com.example.version="0.0.1-beta"

RUN DEBIAN_FRONTEND=noninteractive && \
  apt-get update && \
  apt-get install -y gpg && \
  apt-get install -y cmake && \
  apt-get install -y git && \
  apt-get install -y wget && \
  apt-get install -y curl && \
  apt-get install -y zlib1g-dev && \
  apt-get install -y ca-certificates && \
  wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-py310_23.9.0-0-Linux-x86_64.sh -O /opt/miniconda.sh && \
  /bin/bash /opt/miniconda.sh -b -p /opt/conda; \
  rm /opt/miniconda.sh

ENV CONDA_DIR=/opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

SHELL ["/bin/bash", "-c"]
# ----------------------------------------
# Geant4 env & G4RT
# ----------------------------------------
RUN conda init && /bin/bash && \
    cd /root/ && git clone --single-branch --branch 20-simulation-output-format-to-hdf https://github.com/dose3d/g4rt.git && \
    conda env create --name geant4 -f g4rt/docs/dev/g4rt.yml && \
    source /opt/conda/etc/profile.d/conda.sh && conda activate geant4 && \
    cd /root/ && mkdir g4rt/build && cd g4rt/build && cmake ../ && make -j 4