[Log_Global]
LogLevel = "debug"
ConsolePattern = "[%^%l%$] %! %v"
FilePattern = "[%Y-%m-%d %H:%M:%S.%e] [%^%l%$] %! %v"
LogDir = "log/"
Console = "true"
LogFileName = "logger.log"

[Log_RunSvc]
LogLevel = "warn"
LogFileName = "run_svc.log"

[Log_D3DCell]
LogLevel = "debug"
Console = "false"
LogFileName = "dose3d.log"

[Log_G4Cout]
LogLevel = "debug"
Console = "true"
LogFileName = "logger.log" # The same as for global logger