[RunSvc]
JobName = "tracks_ana_test"
BeamType = "IAEA" # "gps" IAEA 
# BeamType = "gps" # "gps" IAEA 
PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH pc location
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/BestPHSPs1_10e8hist" # AGH JH File
# GpsMacFileName = "/home/g4rt/instal/dose3d-geant4-linac/scripts/gpsCLiniac.mac"
# PhspInputFileName = "/mnt/e/dose3d/TNSIM157_3x3s2-f0" # lokalizacja Michala
# PhspInputFileName = "/mnt/d/Torrenty/FMDoseLab_3x3_6_110s2-f0" # jh home file 
Physics = "LowE_Penelope"
PrintProgressFrequency = 0.001
NTupleAnalysis = true 
PrimariesAnalysis = false
BeamAnalysis = false
FieldSize = 400 # mm


[PatientGeometry]
Type = "D3DDetector"
# Type = "WaterPhantom"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 0.0
EnviromentSizeX = 400.0
EnviromentSizeY = 400.0
EnviromentSizeZ = 310.0
EnviromentMedium = "G4_Galactic"

[D3DDetector_Detector]
TranslationInLocalFrame = [0.0,0.0,-155.0] # In mm
Geomertry = "dose3d/geo/full_tower.stl"

[D3DDetector_Layer]
Positioning = "dose3d/geo/full_tower.csv"

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
TracksAnalysis = false
Voxelization = [2,2,2]

[WaterPhantom_Detector]
TranslationFromCentre = [0.0,0.0,0.0] # In mm
Voxelization = [1,1,1] # Number of cels in every direction
Size = [400.0,400.0,400.0]
Medium = "G4_WATER" #G4_WATER, PMMA

[WaterPhantom_Scoring]
FullVolume = true
FarmerDoseCalibration = false
TracksAnalysis = false

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0,90.0,180.0,270.0,300.0,315.0,330.0,345.0,0.0,15.0,30.0,45.0,60.0,75.0,90.0]
Particle_Counter_Per_Control_Point = [2e4,5e5,5e5,5e5] #50000,5000000,5000000,5000000,5000000,5000000,5000000,5000000,5000000]

[LogSvc_D3DCell]
LogLevel = "debug"
