[RunSvc]
JobName = "Two towers 2x2x16 - beam centre shifted to one of tour rows"
BeamType = "gps" 
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
GpsMacFileName = "gps/gpsCLinac.mac"
PrintProgressFrequency = 0.01
NTupleAnalysis = true 
FieldType = "Rectangular"
FieldSizeA = 55 # mm
FieldSizeB = 55 # mm

[PatientGeometry]
Type = "D3DDetector"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 125.0
EnviromentSizeX = 80.0
EnviromentSizeY = 80.0
EnviromentSizeZ = 315.0
EnviromentMedium = "Usr_G4AIR20C"
TableConstruction = false


[D3DDetector_Detector]
TranslationInLocalFrame = [0.0,0.0,-150.0] # In mm
Geomertry = "dose3d/geo/OneTower.stl"

[D3DDetector_Layer]
Positioning = "dose3d/geo/november_tower_2x2x32.csv"

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [2,2,2]


[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [45.0]
Particle_Counter_Per_Control_Point = [5e3]

[LogSvc_D3DCell]
LogLevel = "debug"
