[RunSvc]
JobName = "New PHSP Test"
BeamType = "IAEA" 
PhspInputFileName = "/mnt/c/Users/Jakub/Desktop/phsp/Cliniac2100s2-f0" # AGH JH File
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
# GpsMacFileName = "gps/gpsCLinac.mac"
PrintProgressFrequency = 0.01
Physics = "LowE_Penelope"
NTupleAnalysis = true 
PrimariesAnalysis = true
# FieldType = "Rectangular"
FieldType = "Elipsoidal"
FieldSizeA = 90 # mm
FieldSizeB = 90 # mm

[PatientGeometry]
Type = "D3DDetector"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 200.0
EnviromentSizeX = 400.1
EnviromentSizeY = 400.1
EnviromentSizeZ = 400.1
EnviromentMedium = "G4_WATER"

[D3DDetector_Detector]
TranslationInLocalFrame = [0.0,0.0,-195.0] # In mm
Voxelization = [4,4,4] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "G4_WATER" #G4_WATER, PMMA
Voxelization = [2,2,2]
TracksAnalysis = true

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0]
Particle_Counter_Per_Control_Point = [1e4]

[LogSvc_D3DCell]
LogLevel = "debug"