[RunSvc]
JobName = "Multiple tray run test"
BeamType = "IAEA"
# PhspInputFileName = "/mnt/c/Users/Jakub/Desktop/phsp/Cliniac2100s2-f0_v1"
PhspEvtVrtxMultiplicityTreshold = 32
PrintProgressFrequency = 0.005
GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = false
RunAnalysis = true

[GeoSvc]
BuildLinac = true
BuildPatient = true

[PatientGeometry]
Type = "D3DDetector"
PatientIsocentreX = 940.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 40.0
EnviromentSizeX = 2400.0
EnviromentSizeY = 550.0
EnviromentSizeZ = 28.0
EnviromentMedium = "G4_WATER"

[D3DDetector_Detector]
TranslationInLocalFrame = [-1090.0,0.0,10.0] # In mm
Geomertry = "dose3d/geo/Tray/multiple_tray_10x1x1.stl"

[D3DDetector_Layer]
Positioning = "dose3d/geo/Tray/multiple_tray_10x1x1.csv"


[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [2,2,2]

[RunSvc_Plan] 
PlanInputFile = [
    "plan/custom/rot00_open.dat"
]

