[RunSvc]
JobName = "water_phantom_PhisicalPhantom"
BeamType = "IAEA"
# PhspInputFileName = "/sekhemet/scratch/d3df/IAEAPhSp/TNSIM157_10x10s2-f0"
#PhspInputFileName = "/mnt/c/Users/brachwal-agh/Workspace/IAEA/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH Dell-XPS location
# PhspInputFileName = "/etude/brachwal/iaea-phsp/TNSIM157_3x3s2-f0" # AGH LHCBD2 location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH BR location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH BR location
PhspInputFileName = "/mnt/e/14x14merged" # AGH JH File
# PhspInputFileName = "/mnt/e/phsp/TNSIM157_3x3s2-f0" # JH Home File
PhspEvtVrtxMultiplicityTreshold = 25
PrintProgressFrequency = 0.001
Physics = "LowE_Penelope" #  "LowE_Livermore" "LowE_Penelope" "emstandard_opt3"
GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true

[GeoSvc]
BuildLinac = true
BuildPatient = true

[PatientGeometry]
Type = "WaterPhantom"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 195.0
EnviromentSizeX = 1000.0
EnviromentSizeY = 1000.0
EnviromentSizeZ = 1000.0
EnviromentMedium = "G4_WATER"

[WaterPhantom_Detector]
Size = [1.0,1.0,1.0]
Voxelization = [2,2,2] # Number of cells in every direction
Medium = "G4_WATER" #G4_WATER, PMMA

[WaterPhantom_Scoring]
FullVolume = true
FarmerDoseCalibration = false
TracksAnalysis = false

[RunSvc_Plan] # paths can be relative (to PROJECT_DATA) or absolute
# nParticles = [1e4] # Per Control Point
nControlPoints = 1      # This will limit number of ctrl points defined below!
BeamRotation = 0        # This will overwrite Rotation value for all below plan files!
nParticles = 5000      # This will overwrite Rotation value for all below plan files!
PlanInputFile = [
        "plan/custom/cp10x10.dat"
        # "plan/custom/prostate/prostate_imrt_beam0_cp0.dat"
]
