[RunSvc]
JobName = "elipse_study"
BeamType = "IAEA" # "gps" IAEA 
# BeamType = "gps" # "gps" IAEA 
PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
# PhspInputPosition = "s2"
# GpsMacFileName = "/home/g4rt/test/g4rt/scripts/gps/gpsCLiniac_but_parallel.mac"
PrintProgressFrequency = 0.005
NTupleAnalysis = true 
# FieldType = "Rectangular" # "Elipsoidal", "RTPlan"
FieldType = "Elipsoidal" 
FieldSizeA = 40 # mm
FieldSizeB = 70 # mm

[PatientGeometry]
Type = "D3DDetector"
# Type = "WaterPhantom"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 0.0
EnviromentSizeX = 120.0
EnviromentSizeY = 120.0
EnviromentSizeZ = 50.0
EnviromentMedium = "Usr_G4AIR20C"

[D3DDetector_Detector]
TranslationInLocalFrame = [0.0,0.0,0.0] # In mm
Voxelization = [10,10,1] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
TracksAnalysis = true
Voxelization = [2,2,2]

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0]
Particle_Counter_Per_Control_Point = [2e6] #50000,5000000,5000000,5000000,5000000,5000000,5000000,5000000,5000000]

[LogSvc_D3DCell]
LogLevel = "debug"
