[RunSvc]
JobName = "gps_RMPS_emstandard_upgrade"
BeamType = "gps"
GpsMacFileName = "gps/gpsCLinac.mac" # gets file from data/ in this repo
PrintProgressFrequency = 0.01
NTupleAnalysis = true
# Physics = "LowE_Penelope" #"LowE_Penelope"
# FieldType = "Rectangular" # "Elipsoidal", "RTPlan"
FieldType = "Elipsoidal"
FieldSizeA = 25 # mm
FieldSizeB = 25 # mm

[GeoSvc]
BuildLinac = true
BuildPatient = true

[PatientGeometry]
Type = "D3DDetector"
PatientIsocentreX = 0.0
PatientIsocentreY = 0.0
PatientIsocentreZ = 60.5
EnviromentSizeX = 35.0
EnviromentSizeY = 35.0
EnviromentSizeZ = 120.0
EnviromentMedium = "G4_Galactic"

[D3DDetector_Detector]
TranslationInLocalFrame = [0.0,0.0,-60.0] # In mm
Voxelization = [1,1,10] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "RMPS470"
Voxelization = [2,2,2]
TracksAnalysis = true
CellScorer = true
CellVoxelisedScorer = true

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0,30.0]
Particle_Counter_Per_Control_Point = [1e5,2e6]
