name: d3df-patients-env
channels:
  - conda-forge
dependencies:
  - freetype-py=2.5.1
  - loguru=0.7.3
  - matplotlib=3.10.1
  - numpy=2.2.3
  - openpyxl=3.1.5
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0.1
  - pyglet=1.5.27  
  - python=3.12
  - scipy=1.15.2
  - shapely=2.1.1
  - trimesh=4.6.4
  - pip:
      - manifold3d==3.1.0
