[book]
title = "G4RT Documentation"
authors = ["Dose3D Team"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true
extra-watch-dirs = ["./", "./core", "./data", "./externals", "./submodules"]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"

[output.html.search]
enable = true
