[book]
title = "G4RT Documentation"
authors = ["Dose3D Team"]
language = "en"
multilingual = false
src = "./."

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"

[build]
extra-watch-dirs = []   