[RunSvc]
JobName = "static_testbeam10e6x4"
BeamType = "IAEA"
PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # BR AGH pc location
# PhspInputFileName = "/sekhemet/scratch/d3df/IAEAPhSp/TNSIM157_10x10s2-f0"
# PhspInputFileName = "/mnt/c/Users/brachwal-agh/Workspace/IAEA/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH Dell-XPS location
PhspEvtVrtxMultiplicityTreshold = 85
PrintProgressFrequency = 0.01
GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = false
RunAnalysis = true

[GeoSvc]
BuildLinac = true
BuildPatient = true

[PatientGeometry]
Type = "D3DDetector"
PatientIsocentreX = 79.73   # Im'RT origin to CT isocentre translation
PatientIsocentreY = -146.6
PatientIsocentreZ = 139.1
EnviromentSizeX = 190.0
EnviromentSizeY = 190.0
EnviromentSizeZ = 190.0
EnviromentMedium = "Usr_G4AIR20C"
EnviromentPatientEnvelop = "IbaImRT_Box" # Simplified iba Im'RT model

[D3DDetector_Detector]
Positioning = "dose3d/geo/IBA_ImRT/Cell_Positioning_TB21122024_Box.csv"


[D3DDetector_Cell]
TranslationInLocalFrame = [0.00,0.00,0.00] # In mm | 21.12.2024 testbeam (by my conclusion it should be 
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [5,5,5]

[RunSvc_Plan] # paths can be relative (to PROJECT_DATA) or absolute
nControlPoints = 4      # This will limit number of ctrl points defined below!
# BeamRotation = 0       # This will overwrite Rotation value for all below plan files!
# nParticles = 1000     # This will overwrite Rotation value for all below plan files!
PlanInputFile = [
    # "plan/custom/cp5x5.dat"
    # "plan/custom/cp10x10.dat"
    "plan/TB21122024/static/dat/RP.1.2.246.352.71.5.528868944050.1691284.20241220161403_beam0_cp0.dat",
    "plan/TB21122024/static/dat/RP.1.2.246.352.71.5.528868944050.1691284.20241220161403_beam1_cp0.dat",
    "plan/TB21122024/static/dat/RP.1.2.246.352.71.5.528868944050.1691284.20241220161403_beam2_cp0.dat",
    "plan/TB21122024/static/dat/RP.1.2.246.352.71.5.528868944050.1691284.20241220161403_beam3_cp0.dat",
]