[RunSvc]
JobName = "web_job_example"
BeamType = "gps" 
GpsMacFileName = "gps/gpsCLinac_pre.mac"
PhspEvtVrtxMultiplicityTreshold = 10
PrintProgressFrequency = 0.05
GenerateCT = true
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true

[PatientGeometry]
Type = "D3DDetector"
EnviromentSizeX = 50.0
EnviromentSizeY = 50.0
EnviromentSizeZ = 80.0
EnviromentMedium = "G4_Galactic"

[D3DDetector_Detector]
TranslationInLocalFrame = [0.0,0.0,-25.0] # In mm
Voxelization = [3,2,5] # Number of cels in every direction

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [5,5,5]
TracksAnalysis = false

[RunSvc_Plan]
PlanInputFile = [
    "plan/custom/rot00deg_10x10.dat"
]

